### ISSUE TITLE
Archive error

### ISSUE THREAD

**Issue by smarteye520** [Netvent/as-attribution-ios#3]
bitcode bundle could not be generated because '/Users/mac/xxx/Pods/ASAttributionSDK/ASAttributionSDK.framework/ASAttributionSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/mac/xxx/Pods/ASAttributionSDK/ASAttributionSDK.framework/ASAttributionSDK' for architecture arm64

**Comment by yigcal** [comment]
Hi @smarteye520 ,

We released the new version(v0.0.8) with bitcode generation. It should be fixed now. Could you please try the latest version and let us know?

Thanks

**Comment by smarteye520** [comment]
- version 0.0.7
bitcode bundle could not be generated because 
'/Users/xxx/Pods/ASAttributionSDK/ASAttributionSDK.framework/ASAttributionSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/XXX/Pods/ASAttributionSDK/ASAttributionSDK.framework/ASAttributionSDK' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

- version 0.0.8
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.1 compiler: /Users/xxx/Pods/ASAttributionSDK/ASAttributionSDK.framework/Modules/ASAttributionSDK.swiftmodule/arm64-apple-ios.swiftmodule

I am using Xcode 11.1 now, Can you release new version with bitcode generation complied in Swift 5.1?

**Comment by yigcal** [comment]
Hi @smarteye520 ,

We have just released version 0.0.9. Could you please try again?

Thanks

**Comment by smarteye520** [comment]
Hi @yigcal 
I will try it again and let you know.
Thanks.

**Comment by smarteye520** [comment]
Hi @yigcal 
I tried it again but it  says that  None of your spec sources contain a spec satisfying the dependency: 'ASAttributionSDK (~> 0.0.9)'.

I tired it with following instructions
*  pod 'ASAttributionSDK'
 It says that "Installing ASAttributionSDK (0.0.8)" in Terminal.
*  pod 'ASAttributionSDK', '~> 0.0.9'
It says that 
CocoaPods could not find compatible versions for pod "ASAttributionSDK":
  In Podfile:
    ASAttributionSDK (~> 0.0.9)

None of your spec sources contain a spec satisfying the dependency: `ASAttributionSDK (~> 0.0.9)`.
![Screen Shot 2020-04-08 at 8 06 11 AM](https://user-images.githubusercontent.com/47221918/78788264-29eec280-7971-11ea-91b5-526fe1b05fde.png)
![Screen Shot 2020-04-08 at 8 03 20 AM](https://user-images.githubusercontent.com/47221918/78788276-2e1ae000-7971-11ea-8c0e-698e14de162b.png)

**Comment by yigcal** [comment]
Hi @smarteye520,

Could you please try "pod update" instead of "pod install"?

**Comment by smarteye520** [comment]
Hi @yigcal 
Yes, I installed version 0.0.9 with "pod update".
But I got following error  with version 0.0.9
I'm using Xcode 11.1 and I requested new version complied in Swift 5.1  before.

Module compiled with Swift 5.2 cannot be imported by the Swift 5.1 compiler: /Users/zhexing/Documents/Develop/AYM_Kids-App/Pods/ASAttributionSDK/ASAttributionSDK.framework/Modules/ASAttributionSDK.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by yigcal** [comment]
Hi @smarteye520,

While we are releasing a new version, we always try to keep our versions to be compatible with latest versions of xcode and swift. Is it possible for you to update your xcode if there is nothing which blocks this update?

**Comment by smarteye520** [comment]
It's impossible for me to update my Xcode currently, So I didn't use version 0.0.8(complied in Swift 5.1.2)  and requested new version complied in Swift 5.0 or Swift 5.1 again.
Please understand me.
Thanks.

**Comment by yigcal** [comment]
Hi @smarteye520 ,

Please try the version 1.0.0.

**Comment by smarteye520** [comment]
Okay, Thanks.
